### ISSUE TITLE
[Feature Request] Add more config options

### ISSUE THREAD

**Issue by xR4YM0ND** [TelloVilla/Sprinklerz#2]
Would be awesome to:

- disable the bonemeal affection via config
- set watering / hydration range for each sprinkler (copper = 1 block, iron = 2 blocks, etc)

**Comment by TelloVilla** [comment]
Coming in next update. I added a config option for hydration range for each tier, the ability to turn off the bonemeal effect per tier, and the ability to turn it off completely.
