### ISSUE TITLE
[Feature Request] Upside down Sprinklers / placed on ceiling

### ISSUE THREAD

**Issue by xR4YM0ND** [TelloVilla/Sprinklerz#3]
Would be nice to have sprinklers place on the ceiling in a greenhouse

~ 3 to 5 blocks above the crops facing downwards

also if a sprinkler is elevated the water should drop down on the farmland 1 - 5 blocks maybe

if you decide to implement this could you add a config option for that as well pls

**Comment by TelloVilla** [comment]
I'll see what I can do, this is a little more difficult than it sounds because of the way sprinklers actually hydrate blocks

**Comment by xR4YM0ND** [comment]
Yep this feature would be way more advanced.

**Comment by TelloVilla** [comment]
implemented in 0.5 version
