### ISSUE TITLE
[Feature Request] Set vanilla water fluid hydration radius

### ISSUE THREAD

**Issue by xR4YM0ND** [TelloVilla/Sprinklerz#4]
We currently have water hydration (liquid water) set to 2 instead of 4 blocks.

Would be awesome to have that as a extra in the config:

`"default_water_hydration_radius": 4,`

We really need this feature for our modpack aged, if we wanna us Sprinklerz

~ We currently use Moisturization

**Comment by TelloVilla** [comment]
After looking at that mod I see that mine is similar and I would rather not just copy the functionality of that mod. I just want to stick to sprinklers, sorry.

**Comment by xR4YM0ND** [comment]
Understand that.
