### ISSUE TITLE
[Bug] Items have a copper texture on the left side

### ISSUE THREAD

**Issue by xR4YM0ND** [TelloVilla/Sprinklerz#5]
All item textures have a copper ish pixelbar on the left side of the texture in the hotbar.

I've seen that the item textures get generated.
May you implement a custom texture for every sprinkler.

**Comment by TelloVilla** [comment]
Fixed the textures. The issue was that the model textures had a part on the underside which isn't visible in block form painted copper but in item form it shows up.
