### ISSUE TITLE
Sprinkler does not check if block is able to be grown before attempting to grow it

### ISSUE THREAD

**Issue by TheWinABagel** [TelloVilla/Sprinklerz#7]
The if statement [here](https://github.com/TelloVilla/Sprinklerz/blob/8aa2bdbc7f9aa867e4ff8001a40e89104b1616bb/common/src/main/java/com/tellovilla/sprinklerz/entity/block/SprinklerBlockEntity.java#L128) does not check Fertilizable#isFertilizable, which can result in attempting to grow blocks that are not able to be grown (ie fully grown blocks), which can result in a crash ([report](https://pastebin.com/mbewVBDv)).

This is on a fabric server, using Sprinklerz version 0.5.
Fabric API 0.91.0 and Loader version 14.25

**Comment by TelloVilla** [comment]
Thank you, I completely forgot cocoa beans where a thing and didn't think to test them. Should be fixed with 0.5.1.
