### ISSUE TITLE
Sprinklerz error

### ISSUE THREAD

**Issue by Paxx3** [TelloVilla/Sprinklerz#8]
Hello, there is some error about sprinklez.

Here is my log in case: 

[latest.log](https://github.com/TelloVilla/Sprinklerz/files/14395025/latest.log)

and here is a quick screenshot : https://prnt.sc/-54S8KxELBmN

**Comment by TelloVilla** [comment]
I think this is related to leftover resource files for a test item. Should be removed and fixed with 0.5.1
